
server:
  port: 8081

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/abc"
    username: "root"
    password: "abc"
    platform: "mysql"
  jpa:
    hibernate:
      ddl-auto: "create"
    database-platform: org.hibernate.dialect.MySQL8Dialect

  data:
    web:
      pageable:
        default-page-size: 10

logging:
  level:
    org:
      springframework:
        security: trace